fix: Jsonld fixes
hyperledger/aries-framework-javascript pull request #1412
Opened 2023-03-30 13:47 UTC by NB-MikeRichardson

1. Fix the JSONLD_VC format string (it was missing a "v" character).

2. Remove the check credential proofType === request proofType. I believe this check is unnecessary (and always fails when testing with aca-py)

2023-03-30 14:07 UTC, TimoGlastra requested changes
the v prefix changes makes sense, but I think we need to keep the proof type check

2023-03-30 14:10 UTC, NB-MikeRichardson commented on packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormatService.ts
> -    }
We are getting "assertionMethod" in the credential but the request proof type is undefined. I can't see anywhere in our code were we set proof type for an outgoing credential request, hence why I was thinking the test is superfluous. Unless I've missed something

2023-03-30 14:11 UTC, NB-MikeRichardson commented on packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormatService.ts
> -    }
The other possibility is that the incoming test data is wrong, and credential proof type should not be set which would imply a problem somewhere else than AFJ code.

2023-03-30 14:21 UTC, NB-MikeRichardson commented on packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormatService.ts
> -    }
I'll do some investigation and see what I can find.

2023-03-31 06:52 UTC, NB-MikeRichardson commented on packages/core/src/modules/credentials/formats/jsonld/JsonLdCredentialFormatService.ts
> -    }
OK so I discovered we copy proof type and proof puprose from the offer to the request so I guess that means there is something wrong on the incoming offer message that needs investigating.

I've put the check back in. This PR can now be merged with just the one fix.

2023-03-31 14:12 UTC, TimoGlastra approved these changes

2023-04-03 12:03 UTC, merged