fix(anoncreds): wrong key name for predicates in proof object
hyperledger/aries-framework-javascript pull request #1517
Opened 2023-07-21 14:21 UTC by 2mau

2023-07-21 14:23 UTC, TimoGlastra approved these changes

2023-07-24 06:53 UTC, TimoGlastra commented
There are some errors with the type checking

2023-07-26 15:15 UTC, genaris requested changes

2023-07-26 15:15 UTC, genaris commented on .github/workflows/continuous-deployment.yml
> +          persist-credentials: false
I think this change should be reverted from this PR

2023-07-26 16:22 UTC, merged