feat: Added attachment extension
hyperledger/aries-framework-javascript pull request #266
Opened 2021-05-12 15:09 UTC by blu3beri

Added the extension to the attachment decorator and renamed the attachment property on the issue and verify messages to avoid confliction.

Has been added for the support of linking credentials to attachments.

Signed-off-by: Berend Sliedrecht <berend@animo.id>

2021-05-15 13:21 UTC, TimoGlastra requested changes
Thanks @blu3beri, one small suggestion

2021-05-15 13:21 UTC, TimoGlastra commented on src/decorators/attachment/AttachmentExtension.ts
> +      return this.attachments?.find((attachment) => attachment.id === id.substring(0, 64))
We shouldn't truncate the `id` property here, it should just match the two string values.

Truncating can be done on a higher level

2021-05-18 09:09 UTC, TimoGlastra approved these changes

2021-05-21 10:22 UTC, jakubkoci approved these changes
Nice 👍

2021-05-21 13:50 UTC, merged