Feature/proofList
hyperledger/aries-framework-javascript pull request #329
Opened 2021-06-17 19:22 UTC by TheTreek

Added new object that contains the arrays of potential credentials for proof requests
getRequestedCredentialsForProofRequest returns the new object
Added autoSelectCredentialsForProofRequest to have similar functionality as before
Indy credential info is now stored in RequestedPredicate and RequestedAttribute objects

2021-06-18 14:50 UTC, TimoGlastra requested changes
This is looking great! thanks @TheThreek.

I have a few small suggestions

2021-06-18 14:50 UTC, TimoGlastra commented on package-lock.json
> +{
We use yarn instead of NPM. Could you remove the package-lock in favour of the yarn.lock?

2021-06-18 14:50 UTC, TimoGlastra commented on src/modules/proofs/ProofsModule.ts
> +   * @returns RetrievedCredential object
```suggestion
   * @returns RetrievedCredentials object
```

2021-06-18 14:50 UTC, TimoGlastra commented on src/modules/proofs/services/ProofService.ts
> +   * @returns RetrievedCredential object
```suggestion
   * @returns RetrievedCredentials object
```

2021-06-18 14:50 UTC, TimoGlastra commented on src/storage/fs/index.ts
> +export * from './ReactNativeFileSystem'
We can't export this from the framework root as that means you automatically import `fs` if you import anything from the framework. `fs` is not available in React Native

2021-06-18 14:50 UTC, TimoGlastra commented on src/modules/proofs/models/RequestedCredentials.ts
> +    this.selfAttestedAttributes = options.selfAttestedAttributes ?? {}
I think we should keep the `if (options)` here. Otherwise you'd get weir behaviour when transforming from json to class

2021-06-18 23:20 UTC, TimoGlastra approved these changes
LGTM

2021-06-21 18:15 UTC, JamesKEbert approved these changes
Looks good to me @TheTreek, thanks for your efforts here!

2021-06-22 05:40 UTC, merged