Documentation - Agent setup
hyperledger/aries-framework-javascript pull request #420
Opened 2021-08-10 02:47 UTC by MosCD3

As usual, needs some linguistics review

2021-08-13 07:16 UTC, anagoessens reviewed
Some language/grammar suggestions.

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +Note: You do not need genesis file if you are creating a connection between your agent and other agent for exchanging simple messages.
```suggestion
Note: You do not need the genesis file if you are creating a connection between your Agent and another Agent for exchanging simple messages.
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +You will need mediator agent if you are going to deal with VC (Verifiable Credentials), however, you can ignore the mediator step if you are creating an Agent for merely connecting directly to other
```suggestion
You will need a mediator Agent if you are going to deal with VC (Verifiable Credentials), however, you can ignore the mediator step if you are creating an Agent for the sole purpose of exchanging messages with another Agent. 
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +Example: If you are testing with VCs, you can use [Indicio Public Mediator](https://indicio-tech.github.io/mediator/)
```suggestion
Example: If you are testing VC related functionality and need a mediator, you can use the [Indicio Public Mediator](https://indicio-tech.github.io/mediator/).
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +- Head to [Indicio Public Mediator](https://indicio-tech.github.io/mediator/)
```suggestion
- Head to [Indicio Public Mediator](https://indicio-tech.github.io/mediator/).
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +- Copy mediator invite url and save it (i.e. MEDIATOR_INVITE = "url")
```suggestion
- Copy mediator invite url and save it (i.e. MEDIATOR_INVITE = "url").
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +Note: if the invite url use insecure http you will have to adjust your code to allow insecure traffic
```suggestion
Note: If the invite url uses insecure http you will have to adjust your code to allow for insecure traffic.
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +- Instructions for [iOS](https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http)
```suggestion
- Instructions for [iOS](https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http).
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +- Instructions for [Android](https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie)
```suggestion
- Instructions for [Android](https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie).
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +More about [Mediators](3-routing.md)
```suggestion
More about [Mediators](3-routing.md).
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +  //Inbound transport are currently built-in and you don't need to create it
```suggestion
  //Inbound transports are currently built-in, you don't need to create them.
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +More about [Transports](1-transports.md)
```suggestion
More about [Transports](1-transports.md).
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +After creating the Agent object and configuring it with all configuration, we initialize the Agent
```suggestion
After creating the Agent object and configuring it, we initialize the Agent.
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +After you successfully initialize your Agent, you will notice most of the hard work is done by the underlying Aries/Indy framework however, you as a controller need to intercept at some situations le
```suggestion
After you successfully initialize your Agent, you will notice that most of the hard work is being done by the underlying Aries/Indy framework. However, you as a controller will need to intercept in some situations when there is a state change (like when you need to accept an offered credential or reject/accept an incoming connection request). This is done through state change handlers.
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +Example: This sample Credential callback shows how to detect that a credential is received and show the user the credential asserts and give the option to accept/reject the offered credential
```suggestion
Example: This sample credential callback shows how to detect that a credential is received, show the user the credential asserts and give the option to accept/reject the offered credential.
```

2021-08-13 07:16 UTC, anagoessens commented on docs/getting-started/0-agent.md
> +More about [Credentials](5-credentials.md)
```suggestion
More about [Credentials](5-credentials.md).
```

2021-08-14 08:17 UTC, blu3beri commented on docs/getting-started/0-agent.md
> +Example: Lets say your agent will accept a verifiable credential from trinsic.id, you will probably need to download the genesis file for Sovrin network
let's

2021-08-21 12:46 UTC, TimoGlastra requested changes
Great work @MosCD3!

I've left some comments. Do you think it would also be useful to handle creating a connection in this guide, or would you say that is a topic for another file?

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +```
I think we shouldn't encourage people to download a genesis transaction file on each startup. I'd recommend the following approach: 

This also removes the need to use platform specific file system libraries (as it is handled by the framework)

```ts
const BCOVRIN_TEST_GENESIS = `{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"138.197.138.255","client_port":9702,"node_ip":"138.197.138.255","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"138.197.138.255","client_port":9704,"node_ip":"138.197.138.255","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"138.197.138.255","client_port":9706,"node_ip":"138.197.138.255","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"138.197.138.255","client_port":9708,"node_ip":"138.197.138.255","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}`

const agentConfig = {
   poolName: 'BCovrin Test'
   genesisTransactions: BCOVRIN_TEST_GENESIS
}
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +You will need a mediator Agent if you are going to deal with VC (Verifiable Credentials), however, you can ignore the mediator step if you are creating an Agent for the sole purpose of exchanging mes
This assumes mobile environments. Mediators are only needed when you can't host an endpoint to receive messages yourself (this is the case on mobile environments). It is required for all exchanges on mobile, not only when dealing with VCs

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +- Instructions for [Android](https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie).
This also assumes mobile environments. I'm okay with targeting mobile environments but we should make it a getting started in React Native guide in that case

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +      label: 'my-agent9',
```suggestion
      label: 'My Agent',
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +      walletCredentials: {key: 'testkey0230482304823042304244'},
```suggestion
      walletConfig: {
      	id: 'WalletId',
      	key: 'TestKey',
      },
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +      genesisPath,
```suggestion
      poolName: 'BCovrin Test',
      genesisTransactions: BCOVRIN_TEST_GENESIS,
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +```
```suggestion

### Outbound transports

Outbound transport are for sending messages. Outbound transports can optionally be used for receiving messages (e.g. in the case of a mediator). Currently two transports are supported as part of the framework, HTTP and WebSockets.

\`\`\`ts
  // For sending messages to http endpoints
  const httpOutboundTransport = new HttpOutboundTransport();
  agent.registerOutboundTransport(httpOutboundTransport);
  
  // For sending messages to ws endpoints
  const wsOutboundTransport = new WsOutboundTransport();
  agent.registerOutboundTransport(wsOutboundTransport);
\`\`\`

### Inbound transports

Inbound transports are for receiving messages. The inbound transports are only available in NodeJS environments, as we need to start a server to expose an HTTP endpoint and WebSocket server. You can import the inbound transports from the `@aries-framework/node` package

\`\`\`ts
  // For receiving messages on an HTTP endpoint
  const httpInboundTransport = new HttpInboundTransport({ port: 3000 });
  agent.registerInboundTransport(httpInboundTransport);
  
  // For receiving messages on an WS endpoint
  const wsInboundTransport = new WsInboundTransport({ port: 30001 });
  agent.registerInboundTransport(wsInboundTransport);
\`\`\`
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +```
Please remove the backticks, but github was struggling with the backtikcs in the suggestions

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +//Its highly recommended to wrap the initialization flow in a try/catch block
```suggestion
// It's highly recommended to wrap the initialization flow in a try/catch block 
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +### 6- Handling State Changes
```suggestion
### 7- Handling State Changes
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +### 1- Import statements
I'd prefer to use a dot, or add a space between the number or hyphen

```suggestion
### 1. Import statements
```

```suggestion
### 1 - Import statements
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +);
```suggestion
agent.events.on<BasicMessageReceivedEvent>(
	AgentEventTypes.AgentMessageReceived,
    handleBasicMessageReceive
)

agent.events.on<CredentialStateChangedEvent>(
  CredentialEventTypes.CredentialStateChanged,
  // Custom callback for handling any state change when offering/receiving VCs
  handleCredentialStateChange
)

agent.events.on<ConnectionStateChangedEvent>(
  ConnectionEventTypes.ConnectionStateChanged,
  // Custom callback for handling any state change when offering/receiving a connection
  handleConnectionStateChange(event)
)
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +  if (event.payload.credentialRecord.state === 'offer-received') {
```suggestion
  if (event.payload.credentialRecord.state === CredentialState.OfferReceived) {
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +    //On user click "Accept"
```suggestion
    // Display offer to user 
    // On user click "Accept"
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +      autoAcceptConnections: true,
We now have an auto accept "ContentApproved" that I think is good enough for the getting started guide. We could then explain how to manually handle the flow in the in-depth guides

```suggestion
      autoAcceptConnections: true,
      autoAcceptCredentials: AutoAcceptCredential.ContentApproved,
      autoAcceptProofs: AutoAcceptProof.ContentApproved,
```

2021-08-21 12:46 UTC, TimoGlastra commented on docs/getting-started/0-agent.md
> +  }
With content approved mode we can remove this part. 

Maybe adding a `CredentialState.Done` listener to log when the process completed will be helpful

2021-08-21 12:48 UTC, TimoGlastra commented
Some practical notes:
- DCO is failing. I think it would be easiest to squash all commits into a single commit
- Formatting is failing. you can run `yarn format` to automatically fix this
- I'm not sure why there are so many changes that are unrelated to this PR. There's also some conflicts now. I'd try to merge with main to see if that fixes it

2021-08-23 06:32 UTC, MosCD3 commented
@TimoGlastra I would suggest adding all imports in one place, as adding each import to its respective blocks could confuse the developer into thinking that this code black is in a different file or component. 
Many developers tend to copy/past the code from the guide, so adding all imports in one step will make it easier

2021-09-02 13:15 UTC, closed without merging