Feature/question answer
hyperledger/aries-framework-javascript pull request #557
Opened 2021-12-01 17:28 UTC by seajensen

# Summary of Changes

Added a question answer module (https://github.com/hyperledger/aries-rfcs/blob/main/features/0113-question-answer/README.md) to send and receive question messages and to send and receive answer messages with a valid response. 

# Pull Request Checklist

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [x] Added **tests** for changed code (run `scripts/preflight` to run tests and check code style).
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code and new or modified features.

2021-12-01 21:29 UTC, TimoGlastra requested changes
Nice work @seajensen.

Only thing I'm thinking is whether we want to put this in core or ext? E.g push notifications lives in ext, QA is also not part of AIP so should it also live in ext? Would be good to have some consistency in what goed where, but I do see the potential of this getting added to the core package.

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/QuestionAnswerModule.ts
> +  public async sendQuestion(connectionId: string, question: string, validResponses: ValidResponse[], detail?: string) {
With this many parameters I'd lean to an object. In most modules we take the connection/record id as the first parameter and all other properties go into a second config parameter

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/QuestionAnswerModule.ts
> +  public async sendAnswer(connectionId: string, threadId: string, response: string) {
When a record already exists we usually use the record id, maybe we can also use that here?

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/handlers/QuestionAnswerHandler.ts
> +export class QuestionMessageHandler implements Handler {
Usually we only place a single class per file

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/messages/AnswerMessage.ts
> +   * sentTime will be assigned to new Date if not passed, id will be assigned to uuid/v4 if not passed
Outdated comment

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/messages/AnswerMessage.ts
> +  //   public validResponse: ValidResponse[string]
?

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/services/QuestionAnswerService.ts
> +  public async receiveQuestion(messageContext: InboundMessageContext<QuestionMessage>): Promise<QuestionAnswerRecord> {
I think we usually call methods used by the handlers `processXXX`

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/services/QuestionAnswerService.ts
> +    }
```suggestion
    // Assert ready connection
    const connection = messageContext.assertReadyConnection()

```

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/services/QuestionAnswerService.ts
> +      this.logger.error(`Response does not match valid responses`)
Maybe we can throw an error here? It is not clear when calling this that the record won't get updated.

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/QuestionAnswerModule.ts
> +    }
We could then also ditch this check

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/services/QuestionAnswerService.ts
> +      throw error
Why the try/catch here? I don't see it in other places. Maybe the base errors are sufficient here?

2021-12-01 21:29 UTC, TimoGlastra commented on packages/core/src/modules/question-answer/services/QuestionAnswerService.ts
> +   * @todo use connection from message context
Old comment?

2021-12-02 12:14 UTC, genaris commented
> Nice work @seajensen.
> 
> Only thing I'm thinking is whether we want to put this in core or ext? E.g push notifications lives in ext, QA is also not part of AIP so should it also live in ext? Would be good to have some consistency in what goed where, but I do see the potential of this getting added to the core package.

First of all, good work @seajensen! It's great to see how easy it becomes to create modules implementing new protocols in AFJ.

This is a good point @TimoGlastra. I think the choice could depend on the current RFC lifecycle status, which is eventually related to AIPs (i.e. most ACCEPTED RFCs become part of an AIP version). Push Notification Native RFC is currently PROPOSED, so it is not likely to be widely used right now and it's fine in ext repository. In this particular case, Question/Answer is DEMONSTRATED, which is not so different. 

If we choose to put it in aries-javascript-framework-ext repository, I think there are a few classes/methods to be exposed (for instance `BaseRecord` and `createOutboundMessage`). This will be useful also for anyone who wants to use custom protocols in AFJ. I can create a PR including these exports shortly.

2022-01-27 22:27 UTC, TimoGlastra commented
We had a discussion about this during the WG call, but I forgot the outcome. Do we add this to the core of the framework, or make it an extension?

@JamesKEbert @seajensen do you know what the outcome was?

2022-01-29 01:08 UTC, JamesKEbert commented
I unfortunately I was out sick during that WG call, but I recall @seajensen communicating to me that we were going to merge it in.

2022-06-02 16:37 UTC, TimoGlastra approved these changes

2022-06-02 16:37 UTC, TimoGlastra commented
@seajensen if you can resolve the conflicts we can get this merged!

2022-06-05 15:59 UTC, merged