WIP: feat: wip add choice for taa mechanism
hyperledger/aries-framework-javascript pull request #849
Opened 2022-06-13 11:26 UTC by morrieinmaas

todos:
* tests
* ensure this is complete and correct

Signed-off-by: Moriarty <moritz@animo.id>

2022-06-13 11:26 UTC, morrieinmaas commented
closes #707

2022-06-14 09:29 UTC, morrieinmaas commented on packages/core/src/modules/ledger/IndyPool.ts
> +  version: `${number}.${number}` | `${number}`
suggestion in issue description was ``version: `${number}.${number}` `` only. Maybe I'm missing sth but version I found was of format `` `${number}` `` so I added that as alternative type/format

2022-06-14 09:52 UTC, morrieinmaas commented
@TimoGlastra @blu3beri @karimStekelenburg any feedback welcome

2022-06-14 10:10 UTC, TimoGlastra requested changes

2022-06-14 10:10 UTC, TimoGlastra commented on packages/core/src/modules/ledger/LedgerModule.ts
> -  public async registerPublicDid(did: string, verkey: string, alias: string, role?: NymRole) {
If we add the TAA to the indy pool config, there's no need to specify it for each method we call. We can extract it from the indy pool config at a lower level

2022-06-14 10:10 UTC, TimoGlastra commented on packages/core/src/modules/ledger/services/IndyLedgerService.ts
> +    taa?: TransactionAuthorAgreement
same here, we can extract it on a lower level

2022-06-14 10:10 UTC, TimoGlastra commented on packages/core/src/modules/ledger/services/IndyLedgerService.ts
> -        this.getFirstAcceptanceMechanism(authorAgreement),
we can delete this method now

2022-06-14 10:10 UTC, TimoGlastra commented on packages/core/src/modules/ledger/services/IndyLedgerService.ts
> +  private async appendTaa(pool: IndyPool, request: Indy.LedgerRequest, taa?: TransactionAuthorAgreement) {
We pass the pool config to `IndyPool` in the constructor. If we make the taa config available on the `InydPool` we don't have to pass this value around everywhere

2022-06-14 10:11 UTC, TimoGlastra commented
Also could you add some tests?

2022-06-15 08:01 UTC, TimoGlastra approved these changes
This is great @morrieinmaas! 

The new `transactionAuthorAgreement` needs to be documented. Could you also create a PR in aries-javascript-docs to add this property? It should be added here: https://github.com/animo/aries-javascript-docs/blob/main/guides/tutorials/agent-config.md#indyledgers

2022-06-15 08:02 UTC, morrieinmaas commented
> This is great @morrieinmaas!
> 
> The new `transactionAuthorAgreement` needs to be documented. Could you also create a PR in aries-javascript-docs to add this property? It should be added here: https://github.com/animo/aries-javascript-docs/blob/main/guides/tutorials/agent-config.md#indyledgers

Yes I will do!

2022-06-15 08:26 UTC, merged

2022-06-15 11:59 UTC, 2byrds commented
The documentation is growing nicely!